/*
 * QEMU model of the ARM Generic Timer
 *
 * Copyright (c) 2014 Xilinx Inc.
 *
 * Autogenerated by xregqemu.py 2014-09-10.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "qemu/osdep.h"
#include "hw/sysbus.h"
#include "hw/register-dep.h"
#include "qemu/bitops.h"
#include "qapi/error.h"
#include "qemu/log.h"
#include "qemu/timer.h"
#include "hw/arm/arm-system-counter.h"

#ifndef ARM_GEN_TIMER_ERR_DEBUG
#define ARM_GEN_TIMER_ERR_DEBUG 0
#endif

#define DB_PRINT_L(lvl, fmt, args...) do {\
    if (ARM_GEN_TIMER_ERR_DEBUG >= lvl) {\
        qemu_log(TYPE_ARM_GEN_TIMER ": %s:" fmt, __func__, ## args);\
    } \
} while (0);

#define DB_PRINT(fmt, args...) DB_PRINT_L(1, fmt, ## args)


#define TYPE_ARM_GEN_TIMER              "arm.generic-timer"
#define TYPE_ARM_GEN_TIMER_EVENT        "arm.generic-timer-event"

#define ARM_GEN_TIMER(obj) \
     OBJECT_CHECK(ARMGenTimer, (obj), TYPE_ARM_GEN_TIMER)

#define ARM_GEN_TIMER_EVENT(obj) \
     OBJECT_CHECK(ARMGenTimerEvent, (obj), TYPE_ARM_GEN_TIMER_EVENT)

DEP_REG32(COUNTER_CONTROL_REGISTER, 0x0)
    DEP_FIELD(COUNTER_CONTROL_REGISTER, EN, 1, 1)
    DEP_FIELD(COUNTER_CONTROL_REGISTER, HDBG, 1, 0)
DEP_REG32(COUNTER_STATUS_REGISTER, 0x4)
    DEP_FIELD(COUNTER_STATUS_REGISTER, DBGH, 1, 1)
DEP_REG32(CURRENT_COUNTER_VALUE_LOWER_REGISTER, 0x8)
DEP_REG32(CURRENT_COUNTER_VALUE_UPPER_REGISTER, 0xc)
DEP_REG32(BASE_FREQUENCY_ID_REGISTER, 0x20)

#define R_MAX (R_BASE_FREQUENCY_ID_REGISTER + 1)

/* Our timing backend (QEMU_CLOCK_VIRTUAL) has a fixed, non-configurable
 * frequency, i.e. keeps time in units of ns.
 *
 * NOTE: This macro is not a configurable parameter, it is a fixed
 * characteristic of the backend used to implement this System Counter model.
 * To change the freq presented by this System Counter (and thus by ARM Generic
 * Timers) change the freq-hz object property, not this macro. */
#define CLK_FREQ_HZ 1000000000 /* 1 GHz */

typedef struct ARMGenTimerEvent {
    ARMSystemCounterEvent parent_obj;

    QLIST_ENTRY(ARMGenTimerEvent) list_entry;

    QEMUTimer timer;
} ARMGenTimerEvent;

typedef struct ARMGenTimer {
    SysBusDevice parent_obj;
    MemoryRegion iomem;

    bool enabled;
    uint64_t tick_offset;
    uint32_t freq_hz; /* the modeled System Counter ticks at this freq */
    uint32_t scale; /* relative to the timing backend */

    QLIST_HEAD(se_list_head, ARMGenTimerEvent) slave_events;

    uint32_t regs[R_MAX];
    DepRegisterInfo regs_info[R_MAX];
} ARMGenTimer;

static void counter_control_postw(DepRegisterInfo *reg, uint64_t val64)
{
    ARMGenTimer *s = ARM_GEN_TIMER(reg->opaque);
    bool new_status = extract32(s->regs[R_COUNTER_CONTROL_REGISTER],
                                R_COUNTER_CONTROL_REGISTER_EN_SHIFT,
                                R_COUNTER_CONTROL_REGISTER_EN_LENGTH);
    uint64_t current_ticks;

    current_ticks = muldiv64(qemu_clock_get_us(QEMU_CLOCK_VIRTUAL),
                             NANOSECONDS_PER_SECOND, 1000000);

    if ((s->enabled && !new_status) ||
        (!s->enabled && new_status)) {
        /* The timer is being disabled or enabled */
        s->tick_offset = current_ticks - s->tick_offset;
    }

    s->enabled = new_status;
}

static uint64_t couter_low_value_postr(DepRegisterInfo *reg, uint64_t val64)
{
    ARMGenTimer *s = ARM_GEN_TIMER(reg->opaque);
    uint64_t current_ticks, total_ticks;
    uint32_t low_ticks;

    if (s->enabled) {
        current_ticks = muldiv64(qemu_clock_get_us(QEMU_CLOCK_VIRTUAL),
                                 NANOSECONDS_PER_SECOND, 1000000);
        total_ticks = current_ticks - s->tick_offset;
        low_ticks = (uint32_t) total_ticks;
    } else {
        /* Timer is disabled, return the time when it was disabled */
        low_ticks = (uint32_t) s->tick_offset;
    }

    return low_ticks;
}

static uint64_t couter_high_value_postr(DepRegisterInfo *reg, uint64_t val64)
{
    ARMGenTimer *s = ARM_GEN_TIMER(reg->opaque);
    uint64_t current_ticks, total_ticks;
    uint32_t high_ticks;

    if (s->enabled) {
        current_ticks = muldiv64(qemu_clock_get_us(QEMU_CLOCK_VIRTUAL),
                                 NANOSECONDS_PER_SECOND, 1000000);
        total_ticks = current_ticks - s->tick_offset;
        high_ticks = (uint32_t) (total_ticks >> 32);
    } else {
        /* Timer is disabled, return the time when it was disabled */
        high_ticks = (uint32_t) (s->tick_offset >> 32);
    }

    return high_ticks;
}


static DepRegisterAccessInfo arm_gen_timer_regs_info[] = {
    {   .name = "COUNTER_CONTROL_REGISTER",
        .decode.addr = A_COUNTER_CONTROL_REGISTER,
        .rsvd = 0xfffffffc,
        .post_write = counter_control_postw,
    },{ .name = "COUNTER_STATUS_REGISTER",
        .decode.addr = A_COUNTER_STATUS_REGISTER,
        .rsvd = 0xfffffffd, .ro = 0x2,
    },{ .name = "CURRENT_COUNTER_VALUE_LOWER_REGISTER",
        .decode.addr = A_CURRENT_COUNTER_VALUE_LOWER_REGISTER,
        .post_read = couter_low_value_postr,
    },{ .name = "CURRENT_COUNTER_VALUE_UPPER_REGISTER",
        .decode.addr = A_CURRENT_COUNTER_VALUE_UPPER_REGISTER,
        .post_read = couter_high_value_postr,
    },{ .name = "BASE_FREQUENCY_ID_REGISTER",
        .decode.addr = A_BASE_FREQUENCY_ID_REGISTER,
    }
};

static void arm_gen_timer_reset(DeviceState *dev)
{
    ARMGenTimer *s = ARM_GEN_TIMER(dev);
    unsigned int i;

    for (i = 0; i < ARRAY_SIZE(s->regs_info); ++i) {
        dep_register_reset(&s->regs_info[i]);
    }

    s->tick_offset = 0;
    s->enabled = false;
}

static uint64_t arm_gen_timer_read(void *opaque, hwaddr addr, unsigned size)
{
    ARMGenTimer *s = ARM_GEN_TIMER(opaque);
    DepRegisterInfo *r = &s->regs_info[addr / 4];

    if (!r->data) {
        qemu_log("%s: Decode error: read from %" HWADDR_PRIx "\n",
                 object_get_canonical_path(OBJECT(s)),
                 addr);
        return 0;
    }
    return dep_register_read(r);
}

static void arm_gen_timer_write(void *opaque, hwaddr addr, uint64_t value,
                      unsigned size)
{
    ARMGenTimer *s = ARM_GEN_TIMER(opaque);
    DepRegisterInfo *r = &s->regs_info[addr / 4];

    if (!r->data) {
        qemu_log("%s: Decode error: write to %" HWADDR_PRIx "=%" PRIx64 "\n",
                 object_get_canonical_path(OBJECT(s)),
                 addr, value);
        return;
    }
    dep_register_write(r, value, ~0);
}

static void arm_gen_timer_access(MemoryTransaction *tr)
{
    MemTxAttrs attr = tr->attr;
    void *opaque = tr->opaque;
    hwaddr addr = tr->addr;
    unsigned size = tr->size;
    uint64_t value = tr->data.u64;;
    bool is_write = tr->rw;

    if (is_write && !attr.secure) {
        /* Ignore NS writes  */
        qemu_log_mask(LOG_GUEST_ERROR,
                      "Non secure writes to the system timestamp generator " \
                      "are invalid\n");
        return;
    }

    if (is_write) {
        arm_gen_timer_write(opaque, addr, value, size);
    } else {
        tr->data.u64 = arm_gen_timer_read(opaque, addr, size);
    }
}

static const MemoryRegionOps arm_gen_timer_ops = {
    .access = arm_gen_timer_access,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
};

static uint64_t arm_gen_timer_max_count(ARMSystemCounter *asc)
{
    ARMGenTimer *s = ARM_GEN_TIMER(asc);
    return INT64_MAX / s->scale; /* see return type of qemu_clock_get_ns */
}

static unsigned arm_gen_timer_max_delta(ARMSystemCounter *asc)
{
    /* We increment by 1 on every cycle, and support only one clock freq. */
    return 1;
}

static uint64_t arm_gen_timer_count(ARMSystemCounter *asc)
{
    ARMGenTimer *s = ARM_GEN_TIMER(asc);
    uint64_t count_ns = qemu_clock_get_ns(QEMU_CLOCK_VIRTUAL);
    return count_ns / s->scale;
}

static ARMSystemCounterEvent *arm_gen_timer_event_create(
                                        ARMSystemCounter *asc,
                                        ARMSystemCounterEventCb *cb, void *arg)
{
    ARMGenTimer *s = ARM_GEN_TIMER(asc);
    ARMGenTimerEvent *ge =
        ARM_GEN_TIMER_EVENT(object_new(TYPE_ARM_GEN_TIMER_EVENT));
    ARMSystemCounterEvent *e = ARM_SYSTEM_COUNTER_EVENT(ge);
    e->sc = asc;
    timer_init(&ge->timer, QEMU_CLOCK_VIRTUAL, s->scale, cb, arg);
    QLIST_INSERT_HEAD(&s->slave_events, ge, list_entry);
    return e;
}

static void arm_gen_timer_event_destroy(ARMSystemCounterEvent *e)
{
    ARMGenTimerEvent *ge = ARM_GEN_TIMER_EVENT(e);
    e->sc = NULL;
    QLIST_REMOVE(ge, list_entry);
    timer_deinit(&ge->timer);
    object_unref(OBJECT(e));
}

static void arm_gen_timer_event_schedule(ARMSystemCounterEvent *e,
                                              uint64_t time)
{
    ARMGenTimerEvent *ge = ARM_GEN_TIMER_EVENT(e);
    DB_PRINT("%s: slave event sched @ ticks %lx\n",
             object_get_canonical_path(OBJECT(e->sc)), time);
    timer_mod(&ge->timer, time);
}

static void arm_gen_timer_event_cancel(ARMSystemCounterEvent *e)
{
    ARMGenTimerEvent *ge = ARM_GEN_TIMER_EVENT(e);
    DB_PRINT("%s: slave event cancel\n",
             object_get_canonical_path(OBJECT(e->sc)));
    timer_del(&ge->timer);
}

static void arm_gen_timer_realize(DeviceState *dev, Error **errp)
{
    ARMGenTimer *s = ARM_GEN_TIMER(dev);
    const char *prefix = object_get_canonical_path(OBJECT(dev));
    unsigned int i;

    assert(s->freq_hz <= CLK_FREQ_HZ);
    s->scale = CLK_FREQ_HZ / s->freq_hz;

    for (i = 0; i < ARRAY_SIZE(arm_gen_timer_regs_info); ++i) {
        DepRegisterInfo *r =
                    &s->regs_info[arm_gen_timer_regs_info[i].decode.addr / 4];

        *r = (DepRegisterInfo) {
            .data = (uint8_t *)&s->regs[
                    arm_gen_timer_regs_info[i].decode.addr/4],
            .data_size = sizeof(uint32_t),
            .access = &arm_gen_timer_regs_info[i],
            .debug = ARM_GEN_TIMER_ERR_DEBUG,
            .prefix = prefix,
            .opaque = s,
        };
    }
}

static void arm_gen_timer_init(Object *obj)
{
    ARMGenTimer *s = ARM_GEN_TIMER(obj);
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);

    memory_region_init_io(&s->iomem, obj, &arm_gen_timer_ops, s,
                          TYPE_ARM_GEN_TIMER, R_MAX * 4);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription vmstate_arm_gen_timer = {
    .name = TYPE_ARM_GEN_TIMER,
    .version_id = 1,
    .minimum_version_id = 1,
    .minimum_version_id_old = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, ARMGenTimer, R_MAX),
        VMSTATE_END_OF_LIST(),
    }
};

static Property arm_gen_timer_props[] = {
    DEFINE_PROP_UINT32("freq-hz",  ARMGenTimer,    freq_hz,       62500000),
    DEFINE_PROP_END_OF_LIST()
};

static void arm_gen_timer_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    ARMSystemCounterClass *sc = ARM_SYSTEM_COUNTER_CLASS(klass);

    dc->reset = arm_gen_timer_reset;
    dc->realize = arm_gen_timer_realize;
    dc->vmsd = &vmstate_arm_gen_timer;
    dc->props = arm_gen_timer_props;

    sc->max_count = arm_gen_timer_max_count;
    sc->max_delta = arm_gen_timer_max_delta;
    sc->count = arm_gen_timer_count;
    sc->event_create = arm_gen_timer_event_create;
    sc->event_destroy = arm_gen_timer_event_destroy;
    sc->event_schedule = arm_gen_timer_event_schedule;
    sc->event_cancel = arm_gen_timer_event_cancel;
}

static const TypeInfo arm_gen_timer_info[] = {
    {
        .name          = TYPE_ARM_GEN_TIMER,
        .parent        = TYPE_SYS_BUS_DEVICE,
        .instance_size = sizeof(ARMGenTimer),
        .class_init    = arm_gen_timer_class_init,
        .instance_init = arm_gen_timer_init,
        .interfaces = (InterfaceInfo []) {
            {TYPE_ARM_SYSTEM_COUNTER},
        },
    },
    {
        .name          = TYPE_ARM_GEN_TIMER_EVENT,
        .parent        = TYPE_ARM_SYSTEM_COUNTER_EVENT,
        .instance_size = sizeof(ARMGenTimerEvent),
    },
};

DEFINE_TYPES(arm_gen_timer_info)
